### PR TITLE
Watch package json

### PR DESCRIPTION
**Pull request by 2manyvcos**
Solution for #3 

We could also add the option to toggle file watching if you want.

### CODE REVIEW

**Comment by imbhargav5** [comment]
👍  Awesome. Many thanks for the PR @AaronBurmeister .I am going to take a look and test it out. Thanks!

**Comment by imbhargav5** [comment]
An option might be unnecessary because updating the script list when the package.json file changes is the expected behaviour.What do you think @AaronBurmeister ?

**Comment by 2manyvcos** [comment]
You're right. :+1:

**Comment by imbhargav5** [comment]
Awesome. Looks good. Merging!

**Comment by 2manyvcos** [comment]
Cool, thank you.

**Pull request merged**
